# Minimal docker compose stack to run Netbox.
# For testing only, use the netbox-communizy/docker project for production workloads
version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=netbox
      - POSTGRES_PASSWORD=netbox
      - POSTGRES_DB=netbox
  redis:
    image: redis:6-alpine
  netbox:
    # Pull netbox image version from environment
    image: netboxcommunity/netbox:${NETBOX_VERSION-latest}
    depends_on:
      - postgres
      - redis
    ports:
      - ${NETBOX_PORT-8000}:8080
    environment:
      - CORS_ORIGIN_ALLOW_ALL=True
      - DB_NAME=netbox
      - DB_USER=netbox
      - DB_PASSWORD=netbox
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_DATABASE=0
      - REDIS_SSL=false
      - REDIS_CACHE_HOST=redis
      - REDIS_CACHE_DATABASE=1
      - REDIS_CACHE_SSL=false
      - SECRET_KEY=foobar
      - SKIP_STARTUP_SCRIPTS=false
      - SKIP_SUPERUSER=false
      - SUPERUSER_NAME=admin
      - SUPERUSER_EMAIL=admin@example.com
      - SUPERUSER_PASSWORD=admin
      - SUPERUSER_API_TOKEN=${NETBOX_API_TOKEN}
